### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by jagosherred** [spe-uob/2020-HealthcareLake#132]
Identify the requirements and quality attributes derived from interactions with your client that are most likely to have an influence on your system architecture. For example, if your client requires the system to be made available via the web, this will clearly have major implications for your chosen architecture. At a lower level, if your application is expected to push dynamic updates out to your clients, this will also have an impact on your system. A whole range of other requirements-level factors such as system interoperability, data storage/retrieval, security, hardware, interaction devices etc. may also impact your architecture. Once you have explicitly documented these primary architectural drivers, present a high-level architecture diagram of your overall system structure. This architecture section of your portfolio should take no more than 2 pages of A4 in total.

**Comment by joekendal** [comment]
> Comparing these together the most cost-efficient long term is GPC which will benefit our client, Microsoft Azure is the most user-friendly this could increase production time in our team. However, we decided to use AWS as a member of our group already had previous expertise in AWS. 

This is completely untrue. I have experience with GCP and I can guarantee you it is more expensive than AWS. Furthermore, GCP and Azure are years behind AWS if you actually look into it.

**Comment by joekendal** [comment]
User-friendly is subjective but even I'd argue GCP is most user friendly

**Comment by joekendal** [comment]
@LukeBenson21
