### ISSUE TITLE
Acceptance Testing (Evaluation)

### ISSUE THREAD

**Issue by jagosherred** [spe-uob/2020-HealthcareLake#135]
Briefly describe your team's approach to validating your product (acceptance testing) during the later stages of iterative development. In particular, explain and justify the approach used (i.e. Questionnaire, Interview, Observation etc.)

Detail what kinds of users you gained access to and the context/environment your evaluation took place within. Describe how you went about documenting the insights and feedback gained from evaluation. Discuss how you used the findings from your evaluation in refining the final iterations of your system. Provide samples of the evaluation materials where relevant.

This must be a maximum of 2 pages of A4, including the diagrams.

**Comment by joekendal** [comment]
hmm
